CREATE TABLE [dbo].[Pedido]
(
	IdPedido INT NOT NULL IDENTITY(1,1) CONSTRAINT PK_Pedido PRIMARY KEY CLUSTERED(IdPedido), 
    IdCliente INT NOT NULL CONSTRAINT FK_Pedido_Cliente FOREIGN KEY(IdCliente)
    REFERENCES dbo.Cliente(Cedula),
    FechaPedido DATETIME NOT NULL
)
WITH (DATA_COMPRESSION = PAGE)
GO